### ISSUE TITLE
Can we have saveOnTimeSelect as well as saveOnDateSelect?

### ISSUE THREAD

**Issue by asap** [aef-/jquery.filthypillow#27]
Noticed that if someone manually modifies the time, no `fp:save` event is fired. It would be handy to have an event fire when someone manually enters a time and date.

I'd be willing to add this in if you're OK with that.

**Comment by aef-** [comment]
hi asap!

Good idea. I think "saveOnDateSelect" needs to be deprecated, and a save method and datetimechange event need to be added.

That way you could do what you asked for + w/e else with:
```
$elem.on( "fp:datetimechange|fp:datechange|fp:timechange", function( ) {
    $elem.filthypillow( "save" ); or $elem
} );
```

does that work for you? If you'd like to do this or part of this be my guest!!!!!!!!!!!!!!!

**Comment by aef-** [comment]
Pulled in
