### ISSUE TITLE
Datetime picker show time in 24 hour format?

### ISSUE THREAD

**Issue by AndyMacca** [aef-/jquery.filthypillow#29]
Hi,

I want to show and deal with time in 24 hour format rather than AM/PM on the datetime picker.

I have looked through the documentation but not been able to find how to do it.

Is this possible?

Thanks

**Comment by aef-** [comment]
Not at this point, I'll look to adding it in the next couple days though unless you want to take a crack at it.

**Comment by AndyMacca** [comment]
Great. I'm sure you will do a better job than I can :-). What's the likelihood this will be done before end of weekend?

I need this functionality for Monday and would like to use your datetime picker but may have to use another if the functionality is not available by then.

Thanks

**Comment by aef-** [comment]
if you're on a tight schedule, i would check out https://github.com/bevacqua/rome, they did a pretty good job with everything and support military time

**Comment by AndyMacca** [comment]
Cheers, will have a look but already have your datetime picker deployed and working, just needs 24 hour time.

**Comment by AndyMacca** [comment]
Any progress on 24 hour format?

**Comment by terion-name** [comment]
really needed (

**Comment by aef-** [comment]
any pull req I'd be happy to accept, just please include tests. I don't have the time to do this myself at the moment

**Comment by aef-** [comment]
v1.4.0 has 24 hour support using the option:
```enable24HourTime: false```

Please create a new issue for any bugs you may come across
Thanks!
