### ISSUE TITLE
The sixth week of the month is going out of box

### ISSUE THREAD

**Issue by SandeepBiradar** [aef-/jquery.filthypillow#35]
Hi @aef- ,
If a month has six weeks them the sixth month is displaying out of the calendar box.
**Image Link** [image](http://postimg.org/image/z4qhvnc99/f6fc801f/)

> 

Regards
Sandeep

**Comment by aef-** [comment]
Hi Sandeep

Thank you for the bug report. Can you let me know what browser and OS you're on?

Thanks

**Comment by SandeepBiradar** [comment]
Hi @aef- ,
I checked it on win 7 32/64 bit 
google chrome version 48.0.25
Firefox 43.0.1.

Issue is the same, i checked on [Demo Website](http://www.jqueryscript.net/demo/Yet-Another-jQuery-Date-Time-Picker-Plugin-filthypillow/) and running the code locally.

Regards
Sandeep

**Comment by aef-** [comment]
Thanks Sandeep, I'm look to fix it but I'm bit busy so it may be awhile. The issue seems to have to do with the container size. If anyone would like to take it on I'd be happy to pull in their request.

**Comment by aef-** [comment]
Closing this for now, feel free to reopen with a PR or if you see this outside the context of that sandbox. Looks to have more to do with the container than FP
